# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
	{ on = [ "<C-q>" ], run = "close", desc = "Close the current tab, or quit if it is last tab" },
	{ on = [ "U", "f", "m" ], run = "plugin ffmpeg-audio-merge", desc = "ffmpeg replace audio from hovered video with selected one" },
	{ on = [ "<C-n>" ], run = '''
		shell 'dragon-drop --thumb-size 128 --on-top --and-exit --all-compact -- "$@"' --confirm
	''' },
	{ on   = "T", run  = "plugin --sync hide-preview", desc = "Hide or show preview" },
	{ on   = [ "c", "m" ], run  = "plugin chmod", desc = "Chmod on selected files" },
]
