# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
	{ on = [ "<C-q>" ], run = "close", desc = "Close the current tab, or quit if it is last tab" },
	{ on = [ "U", "f", "m" ], run = "plugin ffmpeg-audio-merge", desc = "ffmpeg replace audio from hovered video with selected one" },

	{ on = [ "U", "w" ], run = 'shell "feh --bg-fill \"$0\""', desc = "Set wallpaper" },

	{ on = [ "<C-d>" ], run = '''
		shell 'dragon-drop --thumb-size 128 --on-top --and-exit --all-compact -- "$@"' --confirm
	''' },
	{ on = [ "<C-t>" ], run = '''
		shell '
      args=()
      for file in "$@"; do
        args+=("-p" "$file")
      done
      tdl upload --photo -c "$TG_CHAT" "${args[@]}";
    ' --confirm
	''', sync = true },
	{ on   = [ "c", "m" ], run  = "plugin chmod", desc = "Chmod on selected files" },
	{ on = [ "<C-s>" ], run = "plugin saucenao" },
	{ on = [ "<C-p>" ], run = "plugin pixiv" },
	{ on = [ "m" ], run = "plugin mount" },
	{ on = [ "T" ], run = "plugin toggle-pane min-preview" },

	{ on = [ "g", "r" ], run = "cd /", desc = "Go /" },
	{ on = [ "g", "e" ], run = "cd /etc", desc = "Go /etc" },
	{ on = [ "g", "m" ], run = "cd /mnt", desc = "Go /mnt" },
	{ on = [ "g", "t" ], run = "cd /mnt/trash", desc = "Go /mnt/trash" },
	{ on = [ "g", "s" ], run = "cd $HOME/Source", desc = "Go $HOME/Source" },
]
