# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio          = [ 0, 4, 4 ]
sort_by        = "alphabetical"
linemode       = "size"

[[plugin.prepend_fetchers]]
id = 'mime'
name = '*'
if = '!mime'
run = 'mime-ext'
prio = 'high'

[[plugin.prepend_previewers]]
mime = "video/*"
run = "noop"

[preview]
max_width = 4000
max_height = 4000
image_delay = 0
image_quality = 90
image_filter = 'lanczos3'

[opener]
play = [
	{ run = 'mpv --force-window --use-filedir-conf "$@" >& /dev/null & disown', orphan = true, for = "unix" },
	{ run = 'mpv --force-window "%1"', orphan = true, for = "windows" },
	{ run = '''ffprobe -hide_banner "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
extract = [
	{ run = '7z -bsp1 x "$1"',             desc = "Extract here", for = "unix" },
	{ run = '7z -bsp1 -o"${1%.*}" x "$1"', desc = "Extract subfolder", for = "unix" },
	{ run = 'unar "$1"',             desc = "Unarchive here", for = "unix" },
	{ run = 'tar -xf "$1"',          desc = "Extract tar archive", for = "unix" },
	{ run = 'unar "%1"',             desc = "Extract here", for = "windows" },
]
zip-folder = [
	{ run = 'cd "$1" && 7z a "${1}.7z" .',             desc = "7z", for = "unix" },
]
extract-iso = [
	{ run = '7z x -tiso -o"${1%.*}" "$1"', desc = "Extract iso subfolder", for = "unix" },
]
unrpa = [
	{ run = 'unrpa "$1" --mkdir --path "${1%.*}"', desc = "unrpa to subfolder", for = "unix" },
]
denoise = [
	{ run = 'ffmpeg -i "$1" -af anlmdn -y "${1%.*}.denoised.${1##*.}"', desc = "apply denoise filter", for = "unix" },
]
rpgmv-decrypt = [
	{ run = '[[ -d "$(pwd)/www" ]] && rpgmv-decrypter "$(pwd)/www" || rpgmv-decrypter "$(pwd)"', desc = "Decrypt rpgmaker folder", for = "unix" },
]
unity-decrypt = [
	{ run = 'AssetStudioModCLI "$(pwd)" -m Export -t sprite -o "./$(basename "$(find . -name "*_Data")")_Exported"', desc = "Extract unity assets", for = "unix" },
]
feh = [
  { run = 'feh "$@"', desc = "Show images with feh", for = "unix" },
]
images = [
	{ run = '''
    find "$1" \( -name "*.png" -o -name ".jp*g" \) -print0 | sort -z -n |
      xargs -0 feh --title "%f [%u/%l] %wx%h"
  ''', desc = "Show images in folders recursively", for = "unix" },
	{ run = '''
    find "$1" \( -name "*.png" -o -name ".jp*g" \) -print0 | while IFS= read -r -d '' img; do
      dimensions=$(identify -format "%w %h" "$img" 2>/dev/null)
      if [[ $? -eq 0 ]]; then
        read width height <<< "$dimensions"

        if [[ $width -ge 600 && $height -ge 400 ]]; then
            printf "%s\0" "$img"
        fi
      fi
    done | sort -z -n | xargs -0 feh --title "%f [%u/%l] %wx%h"
  ''', desc = "Show images bigger than 600x400 in folders recursively", for = "unix" },
]
adb-install = [
	{ run = 'adb install "$1"', desc = "Install app to phone through adb", for = "unix" },
]
exe = [
	{ run = 'ghidra "$1" >& /dev/null & disown', desc = "Open in ghidra", for = "unix" },
	{ run = 'wine "$1" >& /dev/null & disown', desc = "Run under wine", for = "unix" },
]
libreoffice = [
	{ run = 'libreoffice "$1" >& /dev/null & disown', desc = "Open in libreoffice", for = "unix" },
]
dnspy = [
	{ run = '''
    fexe() {
      path="$1"
      ret=""
      for _ in {1..5}; do
        ret=$(
        find "$(realpath "$path")" -maxdepth 1 \
          -not -name 'Unity*' -and \
          -not -name 'crashpad_handler.exe' -and \
          -name '*.exe' -print -quit
        )
        [ -f "$ret" ] && break
        path="$path/.."
      done
      echo "$ret"
    }
    export EXE="$(fexe "$PWD")"
    if ! [ -f "$EXE" ]; then
      echo "Executable not found can't lookup lutris config"
      exit 1
    fi

    export GAME=$(
      yq -ej "select(.game.exe == \"$EXE\")" \
      "$HOME"/.config/lutris/games/*.yml
    )
    if [ -z "$GAME" ]; then
      echo "Couldn't find associated lutris game config so prefix can't be resolved"
      exit 1
    fi

    export WINEPREFIX=$(
      echo "$GAME" | jq -r .game.prefix
    )
    export WINEVERSION=$(
      echo "$GAME" | \
      jq -er '.wine.version // empty' || \
      yq -r .wine.version "$HOME/.config/lutris/runners/wine.yml"
    )
    export WINE="$HOME/.local/share/Steam/compatibilitytools.d/$WINEVERSION/files/bin/wine"
    [ -f "$WINE" ] || export WINE="$HOME/.local/share/lutris/runners/wine/$WINEVERSION/bin/wine"

    echo "$WINE"
    echo "$WINEPREFIX"
    /usr/bin/umu-run "$DNSPY_EXE" "$1"
  ''', desc = "DNSPY", for = "unix" },
]

[open]
prepend_rules = [
	# Game shortcuts
	{ name = "*.dll", use = [ "dnspy" ] },
	{ name = "*Game.exe", use = [ "rpgmv-decrypt" ] },
	{ name = "*nw", use = [ "rpgmv-decrypt" ] },
	{ name = "*_Data/", use = [ "unity-decrypt" ] },
	{ name = "*.rpa", use = [ "unrpa" ] },
	{ name = "*.apk", use = [ "adb-install", "extract" ] },

	{ name = "*.{mkv,mp4}", use = [ "play", "denoise" ] },
	{ name = "*.gif", use = [ "play" ] },

	{ name = "*.tar.zst", use = [ "extract" ] },
	{ name = "*.rar", use = [ "extract" ] },

	{ name = "*.exe", use = [ "exe" ] },

	{ name = "*.iso", use = [ "extract-iso" ] },

	{ name = "*.{pdf,docx,doc}", use = [ "libreoffice" ] },

  { mime = "image/*", use = [ "feh" ] },
]
append_rules = [
	{ name = "*/", use = [ "images", "zip-folder" ] },
]
