# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio          = [ 0, 4, 4 ]
sort_by        = "alphabetical"
linemode       = "size"

[opener]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
	{ run = 'mpv --force-window "%1"', orphan = true, for = "windows" },
	{ run = '''ffprobe -hide_banner "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
extract = [
	{ run = '7z x "$1"',             desc = "Extract here", for = "unix" },
	{ run = '7z -o"${1%.*}" x "$1"', desc = "Extract subfolder", for = "unix" },
	{ run = 'unar "$1"',             desc = "Unarchive here", for = "unix" },
	{ run = 'tar -xf "$1"',          desc = "Extract tar archive", for = "unix" },
	{ run = 'unar "%1"',             desc = "Extract here", for = "windows" },
]
extract-iso = [
	{ run = '7z x -tiso -o"${1%.*}" "$1"', desc = "Extract iso subfolder", for = "unix" },
]
unrpa = [
	{ run = 'unrpa "$1" --mkdir --path "${1%.*}"', desc = "unrpa to subfolder", for = "unix" },
]
denoise = [
	{ run = 'ffmpeg -i "$1" -af anlmdn -y "${1%.*}.denoised.${1##*.}"', desc = "apply denoise filter", for = "unix" },
]
rpgmv-decrypt = [
	{ run = 'rpgmv-decrypter "$(pwd)/www"', desc = "Decrypt rpgmaker folder", for = "unix" },
]
adb-install = [
	{ run = 'adb install "$1"', desc = "Install app to phone through adb", for = "unix" },
]

[open]
prepend_rules = [
  # Game shortcuts
	{ name = "*Game.exe", use = [ "rpgmv-decrypt" ] },
	{ name = "*.rpa", use = [ "unrpa" ] },
	{ name = "*.apk", use = [ "adb-install", "extract" ] },

	{ name = "*.{mkv,mp4}", use = [ "play", "denoise" ] },
	{ name = "*.gif", use = [ "play" ] },

	{ name = "*.tar.zst", use = [ "extract" ] },

	{ name = "*.iso", use = [ "extract-iso" ] },
]
