#!/bin/env sh

function notify {
  export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
  notify-send 'Realme Media rescan' "$@"
}

notify 'Waiting 5 seconds.'

sleep 5

notify 'Started'

if adb shell \
	content call \
	--method scan_volume \
	--uri content://media \
	--arg external_primary; then
  notify 'Finished'
else
  notify 'Failed'
  exit 1
fi