#!/bin/env sh

function notify() {
  export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
  notify-send 'Realme Media rescan' "$@"
}

function check() {
  [ "$(adb devices | wc -l)" -eq "2" ]
}

if check; then
  notify 'Waiting 5 seconds.'
  sleep 5
fi

if check; then
  notify 'No devices'
  exit 0
fi

notify 'Started'

if adb shell \
	content call \
	--method scan_volume \
	--uri content://media \
	--arg external_primary; then
  notify 'Finished'
else
  notify 'Failed'
  exit 1
fi