#!/bin/env sh

if [[ "$1" == "--help" ]]; then
	echo "ytosend <title> <map_link> <file>"
	exit 0
fi

if ! command -v youtubeuploader > /dev/null; then
	echo "youtubeuploader is not installed install it before running first"
	exit 1
fi

SKIN="Vaxei (CK Bacon boi 1.0 blue)"
SKIN_WEBSITE="https://ordr.issou.best/skins"
PROFILE_LINK="https://osu.ppy.sh/users/12830952"

TITLE="$1"
FILE="$3"
MAP_LINK="$2"

youtubeuploader \
	-title "$TITLE" \
	-filename "$FILE" \
	-privacy public \
	-tags osu \
	-description \
	"profile: $PROFILE_LINK\nmap: $MAP_LINK\nskin: $SKIN\n$SKIN_WEBSITE"