[font]
size = 20

[font.normal]
family = "JetBrainsMonoNLNF"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNLNF"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNLNF"
style = "Italic"

[window]
opacity = 0.97
